// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
static uint64_t s_action_timeout_reboot;  // Time when reboot ends
bool glue_check_reboot(void) {
  return s_action_timeout_reboot > mg_now(); // Return true if reboot is in progress
}
void glue_start_reboot(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_reboot = mg_now() + 1000; // Start reboot, finish after 1 second
}

static struct mqtt s_mqtt = {true, "yourmqttbroker", "/pt100/pressure", "/pt100/batvol", "/pt100/sensor2", "/pt100/sensor1"};
void glue_get_mqtt(struct mqtt *data) {
  *data = s_mqtt;  // Sync with your device
}
void glue_set_mqtt(struct mqtt *data) {
  s_mqtt = *data; // Sync with your device
}

static struct debug s_debug = {false, false, false, false, false, false};
void glue_get_debug(struct debug *data) {
  *data = s_debug;  // Sync with your device
}
void glue_set_debug(struct debug *data) {
  s_debug = *data; // Sync with your device
}

static uint64_t s_action_timeout_tempoffset2;  // Time when tempoffset2 ends
bool glue_check_tempoffset2(void) {
  return s_action_timeout_tempoffset2 > mg_now(); // Return true if tempoffset2 is in progress
}
void glue_start_tempoffset2(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_tempoffset2 = mg_now() + 1000; // Start tempoffset2, finish after 1 second
}

static uint64_t s_action_timeout_tempoffset1;  // Time when tempoffset1 ends
bool glue_check_tempoffset1(void) {
  return s_action_timeout_tempoffset1 > mg_now(); // Return true if tempoffset1 is in progress
}
void glue_start_tempoffset1(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_tempoffset1 = mg_now() + 1000; // Start tempoffset1, finish after 1 second
}

static struct battery s_battery = {42, 55, "charging"};
void glue_get_battery(struct battery *data) {
  *data = s_battery;  // Sync with your device
}
void glue_set_battery(struct battery *data) {
  s_battery = *data; // Sync with your device
}

static uint64_t s_action_timeout_resetcal2;  // Time when resetcal2 ends
bool glue_check_resetcal2(void) {
  return s_action_timeout_resetcal2 > mg_now(); // Return true if resetcal2 is in progress
}
void glue_start_resetcal2(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_resetcal2 = mg_now() + 1000; // Start resetcal2, finish after 1 second
}

static uint64_t s_action_timeout_resetcal1;  // Time when resetcal1 ends
bool glue_check_resetcal1(void) {
  return s_action_timeout_resetcal1 > mg_now(); // Return true if resetcal1 is in progress
}
void glue_start_resetcal1(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_resetcal1 = mg_now() + 1000; // Start resetcal1, finish after 1 second
}

static uint64_t s_action_timeout_btnlow2;  // Time when btnlow2 ends
bool glue_check_btnlow2(void) {
  return s_action_timeout_btnlow2 > mg_now(); // Return true if btnlow2 is in progress
}
void glue_start_btnlow2(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_btnlow2 = mg_now() + 1000; // Start btnlow2, finish after 1 second
}

static uint64_t s_action_timeout_btnhigh2;  // Time when btnhigh2 ends
bool glue_check_btnhigh2(void) {
  return s_action_timeout_btnhigh2 > mg_now(); // Return true if btnhigh2 is in progress
}
void glue_start_btnhigh2(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_btnhigh2 = mg_now() + 1000; // Start btnhigh2, finish after 1 second
}

static uint64_t s_action_timeout_btnhigh;  // Time when btnhigh ends
bool glue_check_btnhigh(void) {
  return s_action_timeout_btnhigh > mg_now(); // Return true if btnhigh is in progress
}
void glue_start_btnhigh(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_btnhigh = mg_now() + 1000; // Start btnhigh, finish after 1 second
}

static uint64_t s_action_timeout_btnlow;  // Time when btnlow ends
bool glue_check_btnlow(void) {
  return s_action_timeout_btnlow > mg_now(); // Return true if btnlow is in progress
}
void glue_start_btnlow(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_btnlow = mg_now() + 1000; // Start btnlow, finish after 1 second
}

static struct temperature s_temperature = {0, 0};
void glue_get_temperature(struct temperature *data) {
  *data = s_temperature;  // Sync with your device
}
void glue_set_temperature(struct temperature *data) {
  s_temperature = *data; // Sync with your device
}

static struct calibration s_calibration = {0, 0, false, false, 0, 0, 0, 0, 0, 0};
void glue_get_calibration(struct calibration *data) {
  *data = s_calibration;  // Sync with your device
}
void glue_set_calibration(struct calibration *data) {
  s_calibration = *data; // Sync with your device
}

static struct wifi s_wifi = {"", "", false};
void glue_get_wifi(struct wifi *data) {
  *data = s_wifi;  // Sync with your device
}
void glue_set_wifi(struct wifi *data) {
  s_wifi = *data; // Sync with your device
}

static uint64_t s_action_timeout_save_event;  // Time when save_event ends
bool glue_check_save_event(void) {
  return s_action_timeout_save_event > mg_now(); // Return true if save_event is in progress
}
void glue_start_save_event(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_save_event = mg_now() + 1000; // Start save_event, finish after 1 second
}

void glue_reply_events(struct mg_connection *c, struct mg_http_message *hm) {
  const char *headers = "Cache-Control: no-cache\r\n" "Content-Type: application/json\r\n";
  const char *value = "[{\"id\":0,\"timestamp\":12345,\"message\":\"Something failed\",\"priority\":2,\"status\":\"active\",\"notes\":\"some notes\"},{\"id\":1,\"timestamp\":12395,\"message\":\"Something succeeded\",\"priority\":1,\"status\":\"processed\",\"notes\":\"\"}]";
  (void) hm;
  mg_http_reply(c, 200, headers, "%s\n", value);
}