// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

#ifndef MONGOOSE_GLUE_H
#define MONGOOSE_GLUE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "mongoose.h"

#define WIZARD_ENABLE_HTTP 1
#define WIZARD_ENABLE_HTTPS 0
#define WIZARD_ENABLE_HTTP_UI 1
#define WIZARD_ENABLE_HTTP_UI_LOGIN 0

#define WIZARD_ENABLE_WEBSOCKET 0

#define WIZARD_ENABLE_MQTT 0
#define WIZARD_MQTT_URL ""

#define WIZARD_ENABLE_SNTP 0  // Enable time sync.
#define WIZARD_SNTP_TYPE 0    // 0: default Google, 1: DHCP, 2: custom
#define WIZARD_SNTP_URL "udp://time.google.com:123"  // Custom SNTP server URL
#define WIZARD_SNTP_INTERVAL_SECONDS 3600            // Frequency of SNTP syncs

#define WIZARD_DNS_TYPE 0  // 0: default Google, 1: DHCP, 2: custom
#define WIZARD_DNS_URL "udp://8.8.8.8:53"  // Custom DNS server URL
#define WIZARD_CAPTIVE_PORTAL 0
#define WIZARD_ENABLE_MDNS 0
#define WIZARD_MDNS_NAME ""

#define WIZARD_ENABLE_MODBUS 0
#define WIZARD_MODBUS_PORT 502

#ifndef WIZARD_REBOOT_TIMEOUT_MS
#define WIZARD_REBOOT_TIMEOUT_MS 500
#endif

void mongoose_init(void);    // Initialise Mongoose
void mongoose_poll(void);    // Poll Mongoose
extern struct mg_mgr g_mgr;  // Mongoose event manager

void mongoose_set_http_handlers(const char *name, ...);
void mongoose_add_ws_handler(unsigned ms, void (*)(struct mg_connection *));
void mongoose_add_ws_reporter(unsigned ms, const char *name);

struct mongoose_mqtt_handlers {
  struct mg_connection *(*connect_fn)(mg_event_handler_t);
  void (*on_connect_fn)(struct mg_connection *, int);
  void (*on_message_fn)(struct mg_connection *, struct mg_str, struct mg_str);
  void (*on_cmd_fn)(struct mg_connection *, struct mg_mqtt_message *);
};
void mongoose_set_mqtt_handlers(struct mongoose_mqtt_handlers *);

struct mongoose_modbus_handlers {
  bool (*read_reg_fn)(uint16_t address, uint16_t *value);
  bool (*write_reg_fn)(uint16_t address, uint16_t value);
};
void mongoose_set_modbus_handlers(struct mongoose_modbus_handlers *);

void mongoose_set_sntp_handler(void (*fn)(uint64_t epoch_ms));
void mongoose_set_sntp_server(const char *url);

void mongoose_set_auth_handler(int (*fn)(const char *user, const char *pass));

#if WIZARD_ENABLE_MQTT
void glue_lock_init(void);  // Initialise global Mongoose mutex
void glue_lock(void);       // Lock global Mongoose mutex
void glue_unlock(void);     // Unlock global Mongoose mutex
#else
#define glue_lock_init()
#define glue_lock()
#define glue_unlock()
#endif

// Update MDNS name. Works when MDNS is enabled.
void glue_mdns_update_name(const char *newname);

// Increment device change state counter - trigger UI refresh
void glue_update_state(void);

// Firmware Glue

void glue_start_reboot(struct mg_str);  // Start an action
bool glue_check_reboot(void);  // Check if action is still in progress

struct mqtt {
  bool en;
  char broker[50];
  char topic_pressure[30];
  char topic_batvol[30];
  char topic_temp2[30];
  char topic_temp1[30];
};
void glue_get_mqtt(struct mqtt *);
void glue_set_mqtt(struct mqtt *);

struct debug {
  bool boot;
  bool ready;
  bool charge;
  bool op;
  bool ldo;
  bool led;
};
void glue_get_debug(struct debug *);
void glue_set_debug(struct debug *);

void glue_start_tempoffset2(struct mg_str);  // Start an action
bool glue_check_tempoffset2(void);  // Check if action is still in progress

void glue_start_tempoffset1(struct mg_str);  // Start an action
bool glue_check_tempoffset1(void);  // Check if action is still in progress

struct battery {
  int voltage;
  int percent;
  char status[10];
};
void glue_get_battery(struct battery *);
void glue_set_battery(struct battery *);

void glue_start_resetcal2(struct mg_str);  // Start an action
bool glue_check_resetcal2(void);  // Check if action is still in progress

void glue_start_resetcal1(struct mg_str);  // Start an action
bool glue_check_resetcal1(void);  // Check if action is still in progress

void glue_start_btnlow2(struct mg_str);  // Start an action
bool glue_check_btnlow2(void);  // Check if action is still in progress

void glue_start_btnhigh2(struct mg_str);  // Start an action
bool glue_check_btnhigh2(void);  // Check if action is still in progress

void glue_start_btnhigh(struct mg_str);  // Start an action
bool glue_check_btnhigh(void);  // Check if action is still in progress

void glue_start_btnlow(struct mg_str);  // Start an action
bool glue_check_btnlow(void);  // Check if action is still in progress

struct temperature {
  double press;
  double temp1;
  double temp2;
};
void glue_get_temperature(struct temperature *);
void glue_set_temperature(struct temperature *);

struct calibration {
  double tempcal2;
  double tempcal1;
  bool ench2;
  bool ench1;
  int adcl2;
  int adch2;
  int adc2;
  int adcl;
  int adch;
  int adc;
};
void glue_get_calibration(struct calibration *);
void glue_set_calibration(struct calibration *);

struct wifi {
  char ssid[25];
  char password[25];
  bool save;
};
void glue_get_wifi(struct wifi *);
void glue_set_wifi(struct wifi *);

void glue_start_save_event(struct mg_str);  // Start an action
bool glue_check_save_event(void);  // Check if action is still in progress

void glue_reply_events(struct mg_connection *, struct mg_http_message *);

#ifdef __cplusplus
}
#endif
#endif  // MONGOOSE_GLUE_H
